version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.4
jobs:
  publish:
    executor: docker-publish/docker
    steps:
      - setup_remote_docker
      - docker-publish/deploy:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:-$CIRCLE_SHA1}
workflows:
  build_publish:
    jobs:
      - docker-publish/publish:
          deploy: false
          tag: ${CIRCLE_TAG:-$CIRCLE_SHA1}
      - publish:
          requires:
            - docker-publish/publish
          # filters:
          #   branches:
          #     ignore: /.*/
          #   tags:
          #     only: /.*/
