version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.4
workflows:
  build:
    jobs:
      - docker-publish/publish:
          deploy: false
          tag: ${CIRCLE_TAG:-$CIRCLE_SHA1}
  publish:
    jobs:
      - check_and_build_only:
          executor: docker-publish/docker
          steps:
            - docker-publish/deploy:
              image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:-$CIRCLE_SHA1}
