version: 2.1
orbs:
  docker-publish: circleci/docker-publish@0.1.4
jobs:
  publish:
    executor: docker-publish/docker
    steps:
      - setup_remote_docker
      - run:
          name: Load image
          command: |
            export NAME=$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:-$CIRCLE_SHA1}
            docker load --input workspace/docker-image/$NAME.tar
      - docker-publish/deploy:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:-$CIRCLE_SHA1}
workflows:
  build_publish:
    jobs:
      - docker-publish/publish:
          deploy: false
          tag: ${CIRCLE_TAG:-$CIRCLE_SHA1}
          after_build:
            - run:
                name: Save Docker image
                command: |
                  export NAME=$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG:-$CIRCLE_SHA1}
                  mkdir -p docker-image
                  docker save -o docker-image/$NAME.tar $NAME
            - persist_to_workspace:
                root: .
                paths:
                  - docker-image
            - store_artifacts:
                path: docker-image
                destination: docker-image
      - publish:
          requires:
            - docker-publish/publish
          # filters:
          #   branches:
          #     ignore: /.*/
          #   tags:
          #     only: /.*/
