version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: |
            docker build -t $CIRCLE_PROJECT_REPONAME .
      - run:
          name: Save Docker image
          command: |
            mkdir -p docker-image
            docker save -o docker-image/$CIRCLE_PROJECT_REPONAME.tar $CIRCLE_PROJECT_REPONAME
      - persist_to_workspace:
          root: .
          paths:
            - docker-image
      - store_artifacts:
          path: docker-image
          destination: docker-image
  deploy:  
    docker:
      - image: circleci/python:3
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: workspace
      - run:
          name: Load image
          command: |
            docker load --input workspace/docker-image/$CIRCLE_PROJECT_REPONAME.tar
      - run:
          name: Deploy
          command: |
            NAME="$DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME:${CIRCLE_TAG}"
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker tag $CIRCLE_PROJECT_REPONAME $NAME
            docker push $NAME
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            # needed for deploy build
            # ref: https://discuss.circleci.com/t/builds-for-tags-not-triggering/17681/7
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
